# Site settings
title: Joey Battista
email: joeybatts00@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/crispy-barnacle" # the subpath of your site, e.g. /blog/
url: "tusk00.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: tusk00

# Build settings
markdown: kramdown

repository: Tusk00/joeybattista